#!/usr/bin/fish
set err (mktemp)
if ghdl -a {processor,main}.vhd adder/*.vhd 2>$err && ghdl -e testbench 2>$err
    ./testbench
else
    set f (head -n1 $err | string match -r '^[^:\n]+')
    set loc (head -n1 $err | string match -r '(?<=)\d+:\d+')
    cat $err
    rm $err
    sleep 1
    
    micro $f +$loc
end
rm *.o
