#!/usr/bin/env fish
cd (status dirname)
switch $argv[1]
case -r
    set err (mktemp)
    set files src/{package,*/*}.vhd
    string join \n $files
    if ghdl -a $files test/$argv[2].vhd 2>$err && ghdl -e testbench 2>$err
        ./testbench
    else
        set f (head -n1 $err | string match -r '^[^:\n]+')
        set loc (head -n1 $err | string match -r '(?<=)\d+:\d+')
        cat $err
        rm $err
        sleep 1
        if echo $f | grep -qE '\.vhdl?$'
            micro $f +$loc
        end
    end
    
    rm -f ./{**/,}{testbench,*.{o,cf}}
case -s
    set msg $argv[2]
    git add ./{,**}/*
    and git commit -m $msg
    and git push origin main
end
