#!/usr/bin/env fish
switch $argv[1]
case -r
    set err (mktemp)
    if ghdl -a package.vhd adder/*.vhd 2>$err && ghdl -e testbench 2>$err
        ./testbench
        rm testbench *.o *.cf
    else
        set f (head -n1 $err | string match -r '^[^:\n]+')
        set loc (head -n1 $err | string match -r '(?<=)\d+:\d+')
        cat $err
        rm $err
        sleep 1
        
        micro $f +$loc
    end
case -s
    set msg $argv[2]
    git add ./{,**}/*
    and git commit -m $msg
    and git push origin main
end
